version: '3.9'
services:
  psel-be:
    image: node:16.14-alpine
    container_name: psel-be
    working_dir: /psel-backend
    volumes:
      - ./psel-be:/psel-backend
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000 # Porta da aplicação Nest.js
      - JWT_SECRET=jwt_secret
      - DB_USER=postgres
      - DB_PASS=102030
      - DB_HOST=dbP
      - DB_PORT=5432
    command: ["npm", "start"]

  db:
    image: postgres:13
    container_name: dbP
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=102030
    restart: 'always'
